# Generated by Django 5.2.1 on 2025-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='idioma',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pages',
            new_name='paginas',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
